server:
  port: 9933
spring:
  application:
    name: data-agent
  profiles:
    active: private
  datasource:
    url: jdbc:postgresql://localhost:5432/data_agent_tutorial
    username:
    password:
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      base-url: openai协议baseurl(不带v1)，例如 https://dashscope.aliyuncs.com/compatible-mode
      api-key:
      chat:
        options:
          model:
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
  show-sql: true
  pretty-sql: true
  language: kotlin
  client:
    ts:
      path: /ts.zip
    openapi:
      path: /openapi
      ui-path: /openapi-ui
