export const DATA_AGENT_GRAPH_NODE = {
  EVIDENCE_RECALL: 'EVIDENCE_RECALL_NODE',
  SCHEMA_RECALL: 'SCHEME_RECALL_NODE',
  TABLE_RELATION: 'TABLE_RELATION_NODE',
  FEASIBILITY_ASSESSMENT: 'FEASIBILITY_ASSESSMENT_NODE',
  PLANNER: 'PLANNER_NODE',
  HUMAN_FEEDBACK: 'HUMAN_FEEDBACK_NODE',
  PLAN_EXECUTION: 'PLAN_EXECUTE_NODE',
  SQL_GENERATION: 'SQL_GENERATE_NODE',
  SQL_EXECUTION: 'SQL_EXECUTE_NODE',
  PYTHON_GENERATION: 'PYTHON_GENERATE_NODE',
  PYTHON_EXECUTION: 'PYTHON_EXECUTE_NODE',
  PYTHON_ANALYSIS: 'PYTHON_ANALYZE_NODE',
  REPORT_GENERATION: 'REPORT_GENERATOR_NODE',
} as const

export const DATA_AGENT_NODE_ORDER = [
  DATA_AGENT_GRAPH_NODE.EVIDENCE_RECALL,
  DATA_AGENT_GRAPH_NODE.SCHEMA_RECALL,
  DATA_AGENT_GRAPH_NODE.TABLE_RELATION,
  DATA_AGENT_GRAPH_NODE.FEASIBILITY_ASSESSMENT,
  DATA_AGENT_GRAPH_NODE.PLANNER,
  DATA_AGENT_GRAPH_NODE.HUMAN_FEEDBACK,
  DATA_AGENT_GRAPH_NODE.PLAN_EXECUTION,
  DATA_AGENT_GRAPH_NODE.SQL_GENERATION,
  DATA_AGENT_GRAPH_NODE.SQL_EXECUTION,
  DATA_AGENT_GRAPH_NODE.PYTHON_GENERATION,
  DATA_AGENT_GRAPH_NODE.PYTHON_EXECUTION,
  DATA_AGENT_GRAPH_NODE.PYTHON_ANALYSIS,
  DATA_AGENT_GRAPH_NODE.REPORT_GENERATION,
] as const

export const DATA_AGENT_ARTIFACT_OUTPUT = {
  GRAPH_NODE_STREAMING: 'GRAPH_NODE_STREAMING',
  GRAPH_NODE_FINISHED: 'GRAPH_NODE_FINISHED',
} as const

export const DATA_AGENT_MESSAGE_METADATA = {
  DATABASE_ID: 'databaseId',
} as const

export const DATA_AGENT_STATE_KEY_RECALL = {
  REWRITE_QUERY: 'REWRITE_QUERY',
  EVIDENCE: 'EVIDENCE',
  TABLE_SCHEMA: 'TABLE_SCHEME',
  COLUMN_SCHEMA: 'COLUMN_SCHEME',
  TABLE_RELATION: 'TABLE_RELATION_OUTPUT',
} as const
